apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "grafana.serviceAccountName" . }}
      containers:
        - name: grafana
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.config.security.admin_user | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.config.security.admin_password | quote }}
            - name: GF_SERVER_ROOT_URL
              value: {{ .Values.config.server.root_url | quote }}
            - name: GF_DATABASE_TYPE
              value: {{ .Values.config.database.type | quote }}
            - name: GF_DATABASE_PATH
              value: {{ .Values.config.database.path | quote }}
            - name: GF_LOG_MODE
              value: {{ .Values.config.log.mode | quote }}
            - name: GF_LOG_LEVEL
              value: {{ .Values.config.log.level | quote }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard-providers
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: grafana-storage
          {{- if .Values.server.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}-storage
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: grafana-config
          configMap:
            name: {{ include "grafana.fullname" . }}-datasources
        - name: grafana-dashboard-providers
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboard-providers
        - name: grafana-dashboards
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
---
{{- if .Values.server.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grafana.fullname" . }}-storage
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.persistentVolume.size }}
  {{- if .Values.server.persistentVolume.storageClass }}
  storageClassName: {{ .Values.server.persistentVolume.storageClass }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config.datasources | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-dashboard-providers
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.dashboardProviders | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-dashboards
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- range $name, $dashboard := .Values.dashboards.default }}
  {{ $name }}.json: |
    {{- toYaml $dashboard | nindent 4 }}
  {{- end }}
