apiVersion: v2
name: prometheus
description: Prometheus monitoring stack
type: application
version: 0.1.0
appVersion: "2.45.0"
keywords:
  - monitoring
  - prometheus
  - metrics
home: https://prometheus.io/
sources:
  - https://github.com/prometheus/prometheus
maintainers:
  - name: monitoring-team
    email: monitoring@example.com
