# Default values for prometheus
# This is a YAML-formatted file.

# Prometheus server configuration
server:
  image:
    repository: prom/prometheus
    tag: "v2.45.0"
    pullPolicy: IfNotPresent
  
  # Resource configuration
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  # Storage configuration
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: ""
  
  # Service configuration
  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090
  
  # Ingress configuration
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: prometheus.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []

# Prometheus configuration
config:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  
  rule_files:
    - "/etc/prometheus/rules/*.yml"
  
  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
    
    - job_name: 'kubernetes-nodes'
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics

# Alertmanager configuration
alertmanager:
  enabled: true
  image:
    repository: prom/alertmanager
    tag: "v0.25.0"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  persistentVolume:
    enabled: true
    size: 2Gi
  
  service:
    type: ClusterIP
    port: 9093
    targetPort: 9093
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: alertmanager.example.com
        paths:
          - path: /
            pathType: Prefix

# Node exporter for node metrics
nodeExporter:
  enabled: true
  image:
    repository: prom/node-exporter
    tag: "v1.6.1"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 200m
      memory: 180Mi
    requests:
      cpu: 100m
      memory: 90Mi

# Kube-state-metrics for Kubernetes metrics
kubeStateMetrics:
  enabled: true
  image:
    repository: k8s.gcr.io/kube-state-metrics/kube-state-metrics
    tag: "v2.9.2"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
