apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-operator.fullname" . }}
  labels:
    {{- include "prometheus-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prometheus-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prometheus-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "prometheus-operator.serviceAccountName" . }}
      containers:
        - name: prometheus-operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - --kubelet-service=kube-system/kubelet
            - --log-level=info
            - --log-format=logfmt
            - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.68.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-operator.fullname" . }}
  labels:
    {{- include "prometheus-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-operator.selectorLabels" . | nindent 4 }}
