apiVersion: v2
name: grafana
description: Grafana monitoring dashboard
type: application
version: 0.1.0
appVersion: "10.0.0"
keywords:
  - monitoring
  - grafana
  - dashboard
home: https://grafana.com/
sources:
  - https://github.com/grafana/grafana
maintainers:
  - name: monitoring-team
    email: monitoring@example.com
