# Default values for grafana
# This is a YAML-formatted file.

# Grafana server configuration
server:
  image:
    repository: grafana/grafana
    tag: "10.0.0"
    pullPolicy: IfNotPresent
  
  # Resource configuration
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  # Storage configuration
  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: ""
  
  # Service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  
  # Ingress configuration
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: grafana.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []

# Grafana configuration
config:
  # Server settings
  server:
    root_url: "http://grafana.example.com/"
  
  # Security settings
  security:
    admin_user: admin
    admin_password: admin123
  
  # Database settings
  database:
    type: sqlite3
    path: /var/lib/grafana/grafana.db
  
  # Logging
  log:
    mode: console
    level: info
  
  # Data sources
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server:9090
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy

# Dashboard configuration
dashboards:
  default:
    kubernetes-cluster-monitoring:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    kubernetes-pod-monitoring:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    nginx-ingress-controller:
      gnetId: 9614
      revision: 1
      datasource: Prometheus

# Dashboard providers
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

# Service account for RBAC
serviceAccount:
  create: true
  name: grafana
  annotations: {}

# RBAC configuration
rbac:
  create: true
  pspEnabled: false
