apiVersion: v2
name: prometheus-operator
description: Prometheus Operator for Kubernetes
type: application
version: 0.1.0
appVersion: "0.68.0"
keywords:
  - monitoring
  - prometheus
  - operator
home: https://github.com/prometheus-operator/prometheus-operator
sources:
  - https://github.com/prometheus-operator/prometheus-operator
maintainers:
  - name: monitoring-team
    email: monitoring@example.com
